
CREATE TABLE IF NOT EXISTS usuarios (
codigo INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(40) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
profissao VARCHAR(50) NOT NULL,
PRIMARY KEY(codigo)
) DEFAULT charset=utf8;